### PR TITLE
Move doc generation to mkdocs.

### PR DESCRIPTION
**Pull request by mhammond**
The generated "content" (ie, .html layout, #refs etc) is the same as generated by mdbook - all old links should be unchanged.

The other theme etc generated stuff is obviously very different; mkdocs using the 'material' theme.

This is a step toward #2016, although no actual versioning happens here. Note also that I haven't yet tested the CI deploy code fully (although I have manually checked the commands listed should all work correctly in the docker image listed) - so there's a chance some followups will be necessary if I screwed this up.

Rendered version: https://mhammond.github.io/uniffi-rs

### CODE REVIEW

**Review by bendk — APPROVED** [review]
The docs look good to me, I'd say they're overall an improvement.  The one thing I like about the old docs is that the TOC is just a static list rather than dynamically expanded with the disclosure arrows.  Is it possible to do that with mdbook?

That's pretty nit-picky though.  If this makes versioning easier then I'm all for the change.

**Comment by bendk** [comment]
I don't feel strongly at all about the styling.  If more people care, then maybe we could do majority vote.  If not, I think you should get the say since you're doing the work.

**Comment by Sajjon** [comment]
Looks great! 

Is it possible to get more colorful code highlighting?

Screenshot 2024-04-23 at 20 15 10

Would be so much easier to read with more code highlight :)

**Comment by mhammond** [comment]
> Is it possible to get more colorful code highlighting?

I made a small attempt here - see https://github.com/mozilla/uniffi-rs/blob/b0c963710cead64cddad96c71c96ce341ab9a82c/mkdocs.yml#L18-L21 - but I'm erring on the side of just landing this without it, which might help others help work out why it's not working :)

**Pull request merged**
