### PR TITLE
Updating the changelog in preparation of v0.20.0

### PR DESCRIPTION
**Pull request by bendk**
I'm hoping to release v0.20.0, this updates the changelog with the breaking changes.

### CODE REVIEW

**Comment by jplatte** [comment]
I am confused, are you doing 0.20.0 or 0.19.7? 😄

**Comment by bendk** [comment]
> I am confused, are you doing 0.20.0 or 0.19.7? smile

0.19.7.  I updated the description, but was too lazy to fix the branch name.

**Comment by jplatte** [comment]
You also didn't update the commit message or PR description though. I am also confused about "forgot how semver works". Are you referring to the official semver spec that says everything below 1.0 can do breaking changes? That's not relevant to Cargo's interpretation to semver (unfortunately, they even link to the official one..), documented [here](https://doc.rust-lang.org/cargo/reference/resolver.html#semver-compatibility).

**Comment by bendk** [comment]
I guess I'm just confused today.  Looks like this should indeed be a bump to 0.20.0.

**Comment by jplatte** [comment]
… unless you want to declare everything proc-macro as semver-exempt 😄 

(I'll stop commenting on this now, ultimately it isn't that important which version number this is)

**Review by jhugman — APPROVED** [review]
Please accept this rubber stamp LGTM with compliments and best regards.

**Pull request merged**
