### PR TITLE
WIP - Solves #2000 to conditionally enable uniffi::constructor macro 

### PR DESCRIPTION
**Pull request by rafaelbeckel**
The main discussion happened at https://github.com/mozilla/uniffi-rs/issues/2000

This doesn't break any current test case. WIP because it should include new test cases covering some of the examples mentioned in the original discussion, but I'm still figuring out where they should go. I'll do that later this week.

Reviews are welcome.

### CODE REVIEW

**Review by jplatte — COMMENTED** [review]
This doesn't do what you were talking about in #2000. This would make `#[hello::world::uniffi::constructor]` work, but not `#[cfg_attr(something, uniffi::constructor)]`.

**Comment by rafaelbeckel** [comment]
I see; thanks for pointing it out. I went at it with a wrong assumption. I'll get the tests working, they would have caught it earlier.

**Comment by bendk** [comment]
Have you checked out my comment in the issue?  What do you think about the suggested approach?  It's probably a bit more involved, but I can try to refactor some things so that it's not too bad.

**Comment by rafaelbeckel** [comment]
Closing in favor of https://github.com/mozilla/uniffi-rs/pull/2113

**Pull request closed without merging**
