### PR TITLE
[WIP] split backends into their own crate

### PR DESCRIPTION
**Pull request by tarikeshaq**
for #299 

An extremely early draft just for visibility

The change count is very deceptive, because right now I didn't remove anything, only added an extra crate that acts as the backend. Note that 99.9% of the code added here is just straight copied from `uniffi_bindgen/kotlin` to be its own crate. only the `ForiegnLanguageBackend` trait and its implementation are the additions

The process was very straight forward and I can right now generate the bindings using a separate crate without invoking the kotlin code in `uniffi_bindgen` at all. For today, I'll create a concrete list of tasks to make this reviewable and define what a demo might look like (to magnify the impact here, I might have a separate repo setup)

### CODE REVIEW

**Comment by rfk** [comment]
A random thought...one thing that I don't have a good idea about for this multi-crate setup is, how do we maintain the level of test coverage? It starts to make less sense to have example crates with foreign-language tests for a bunch of different languages, when those languages may be implemented in an entirely separate repo. I'm sure it's tractable, just, something to think about :-)

**Comment by tarikeshaq** [comment]
Dropping a couple of thoughts before I forget, I'm trying to figure out what the best testing story here looks like...

- I'll look at how easy it is to get the `udl` file from a published crate, alternatively, I'll see about having our `coverall` crate dynamically returning it's IDL to backend crates... I may be stretching our "separate the tests" story a little too far

- I'm currently doing something very hacky (import the `coverall` crate as a dev dependency, then point the tests at `target/debug/deps` to find the `cdylib`) - I'll try to find a cleaner alternative to this, at worst have this hacky-ness abstracted away from the backend developer and into our test definition macros

**Comment by rfk** [comment]
> I'll look at how easy it is to get the udl file from a published crate

Hrm. Yes, I bet this is quite hard right now, and it seems like the sort of thing that's worth us investing in making easier.

**Comment by tarikeshaq** [comment]
Spent a bit of time today on figuring out how to get the udl file from a crate published on `crates.io`... possible, but it's not pretty, here's what I have working locally:
- As a part of the uniffi_macros::build_tests macro, we send a network request to `https://crates.io/api/v1/crates/coverall/0.12.0/download`, this downloads a tarball that includes the source code...
- We then use a couple of crates to decompress and unpack the tarball, then get to the `.udl` inside `src` directory

It's very hacky, but possible! and if we abstract it away inside our macros it might even be neat! To make sure I don't sink myself into this, I'm pausing on the testing work here for a second and will get back to this tomorrow when I have more time to work with this

**Comment by tarikeshaq** [comment]
preceded by #1157

**Pull request closed without merging**
