### PR TITLE
Fix(swift): invalid redeclaration of 'UniffiForeignFutureTask'

### PR DESCRIPTION
**Pull request by QuentinPerez**
see #2310

### CODE REVIEW

**Review by bendk — COMMENTED** [review]
Looks good, but can you also include the test fixture you ran?  That way we can make sure the fix sticks.  Maybe it could be named something like `futures-multi-crate` and it can be the place we test async issues when multiple crates are involved.

BTW, I think there's another issue here.  What if 1 crate defines multiple async traits?  That can be for another PR though.

**Comment by QuentinPerez** [comment]
closed by https://github.com/mozilla/uniffi-rs/pull/2341

**Comment by bendk** [comment]
Oops, I thought I recognized that code.  I guess we should have preferred this one since the new PR didn't have tests either.  In any case, thanks for the code -- even if it wasn't merged.

**Comment by QuentinPerez** [comment]
My bad, I had not time to add the tests, I was planning to do it during my christmas holidays 🙂

**Pull request closed without merging**
