### PR TITLE
Move callbacks testing code into its own fixture crate for testing 

### PR DESCRIPTION
**Pull request by badboy**
Part of #439

### CODE REVIEW

**Review by mhammond — APPROVED** [review]
This is a great improvement, thanks

**Comment by mhammond** [comment]
except for the test failures 😬

**Comment by rfk** [comment]
I wonder if the failures here are the same underlying cause as https://github.com/mozilla/uniffi-rs/issues/333

**Comment by badboy** [comment]
fun fact: I had the same locally until I renamed stuff. Then they went away, and that's why I pushed it. I'm looking into why that's happening now on CI

**Pull request merged**
