### PR TITLE
build: upgrade `heck` 0.4.1 → 0.5.0, `clap` 4.3.19 → 4.5.4

### PR DESCRIPTION
**Pull request by ErichDonGubler**

### CODE REVIEW

**Review by badboy — CHANGES_REQUESTED** [review]
This seems to pull in new windows crates (and duplicates). We need to double-check this works in m-c.

**Comment by ErichDonGubler** [comment]
@badboy: `mozilla-central` has patch entries that unify 0.48.0 and 0.52.0 together, so this should work transparently. The duplication is actually only visible for dev/test crates, it seems:

```
$ cargo tree -i windows-sys@0.48.0 --target all

windows-sys v0.48.0
├── errno v0.3.2
│   ├── rustix v0.37.25
│   │   └── async-io v1.13.0
│   │       ├── async-global-executor v2.3.1
│   │       │   └── async-std v1.12.0
│   │       │       └── uniffi-example-futures v0.22.0 (/Users/mozilla/workspace/mozilla/uniffi-rs/examples/futures)
│   │       └── async-std v1.12.0 (*)
│   └── rustix v0.38.8
│       └── is-terminal v0.4.9
│           └── criterion v0.5.1
│               └── uniffi-fixture-benchmarks v0.22.0 (/Users/mozilla/workspace/mozilla/uniffi-rs/fixtures/benchmarks)
├── io-lifetimes v1.0.11
│   └── rustix v0.37.25 (*)
├── is-terminal v0.4.9 (*)
├── polling v2.8.0
│   └── async-io v1.13.0 (*)
├── rustix v0.37.25 (*)
└── rustix v0.38.8 (*)
```

**Comment by badboy** [comment]
> @badboy: `mozilla-central` has patch entries that unify 0.48.0 and 0.52.0 together, so this should work transparently. Also, the duplication is actually only visible for dev/test crates, it seems:

Thanks for checking, then we should be good

**Review by badboy — APPROVED** [review]

**Comment by mhammond** [comment]
Any reason to not merge this now?

**Comment by badboy** [comment]
> Any reason to not merge this now?

Nope. That was just me ... forgetting it. Merging now.

**Pull request merged**
