### PR TITLE
Make use of implicit format string arguments

### PR DESCRIPTION
**Pull request by jplatte**
Based on #1259

### CODE REVIEW

**Comment by mhammond** [comment]
I like the string formatting changes (ie, 60d830baa16aa8723184f055c8940951944bdf1f plus the minver bump) - but did you mean to include some of the macro work here too?

**Comment by mhammond** [comment]
(and to be clear, I don't *not* like the macro changes, but they require more than a rubber stamp :)

**Comment by jplatte** [comment]
This is a draft PR because it contains all of the commits from #1259 from the time of creating it. I intend to rebase once that is merged so there will be no more macro changes.

**Review by mhammond — APPROVED** [review]
Thanks!

**Pull request merged**
