### PR TITLE
proc-macro: Some improvements to unresolved types

### PR DESCRIPTION
**Pull request by jplatte**
Related to #1257.

### CODE REVIEW

**Review by bendk — APPROVED** [review]
Looks good, let's merge.

**Comment by jplatte** [comment]
Oh, weird, I didn't see those before. Where I used `values_mut`, the type it is called on *should* be `BTreeMap`, but clearly something is not quite right. I will look into it tomorrow.

**Comment by jplatte** [comment]
Ah, I split local changes into two PRs, the `BTreeMap` change was in #1377. So this just needs a rebase.

**Review by bendk — APPROVED** [review]
Nice, let's merge.

**Pull request merged**
