### PR TITLE
Fix some typos in ADRs and manual

### PR DESCRIPTION
**Pull request by Lonami**
"focussed" is technically an accepted spelling, but it's rather uncommon, so I changed that too.

### CODE REVIEW

**Review by badboy — APPROVED** [review]

**Comment by Lonami** [comment]
I plan to read through the rest of ADRs so I might find more stuff. I'll leave a comment once I'm done.

**Comment by Lonami** [comment]
In `0005-arc-pointers.md` I'm not quite sure what is meant by "this a but" (emphasis mine):

> Thom discusses **this a but** in [this issue](https://github.com/mozilla/uniffi-rs/issues/244) and agrees with the assertion that raw pointer make sense when all the relevant code is generated.

Perhaps it's an English form I'm not used to, but I'm open to suggestions on clearer wording.

**Comment by Lonami** [comment]
In `0007-enable-implementing-bindings-seperately.md` I'm not quite sure what is meant by "testings":

> Expose fixtures for testings

Could it be just "testing" or "tests"?

**Comment by badboy** [comment]
> In `0005-arc-pointers.md` I'm not quite sure what is meant by "this a but" (emphasis mine):
> 
> > Thom discusses **this a but** in [this issue](https://github.com/mozilla/uniffi-rs/issues/244) and agrees with the assertion that raw pointer make sense when all the relevant code is generated.
> 
> Perhaps it's an English form I'm not used to, but I'm open to suggestions on clearer wording.

should be "this a bit"

**Comment by badboy** [comment]
> In `0007-enable-implementing-bindings-seperately.md` I'm not quite sure what is meant by "testings":
> 
> > Expose fixtures for testings
> 
> Could it be just "testing" or "tests"?

"Expose fixtures for testing"

**Comment by Lonami** [comment]
Thanks, should be good to go now.

**Review by badboy — APPROVED** [review]

**Comment by Lonami** [comment]
(Apologies for the constant stream of commits, but as I read more I keep stumbling across typos 😅.)

**Review by badboy — APPROVED** [review]
No worries. Let's merge this, and more things can go into new PRs.

**Pull request merged**
