### PR TITLE
Add a configuration to allow removing `LocalizedError` conformation

### PR DESCRIPTION
**Pull request by crazytonyli**
In Swift, all generated error types conform to `LocalizedError`. The implementation uses a compiler generated string, which is not an appropriate `LocalizedError` implementation.

This PR adds a new config to "uniffi.toml": `error_types_conform_to_localized_error`. When not set, its config value is `true`, which means existing code is not affected by this change.

I looked into adding unit tests, but couldn't find how. Happy to add some though, if anyone can point me to the right direction.

### CODE REVIEW

**Comment by mhammond** [comment]
Thanks! Can you please explain why you'd want to opt-out of this? It should get a mention at https://github.com/mozilla/uniffi-rs/blob/main/docs/manual/src/swift/configuration.md, so maybe briefly explaining the rationale there too would be good.

> error_types_conform_to_localized_error. When not set, its config value is true, which means existing code is not affected by this change.

Could we maybe negate this - use a name where the default being `false` covers existing code?

**Comment by crazytonyli** [comment]
> Can you please explain why you'd want to opt-out of this?

A couple of reasons:
1. The `errorDescription` function is supposed to return ["a specialized error that provides localized messages describing the error and why it occurred."](https://developer.apple.com/documentation/foundation/localizederror). The implemented used here `String(reflecting:)` does not match that API design.

```swift
$ swift repl
Welcome to Apple Swift version 6.0.2 (swiftlang-6.0.2.1.2 clang-1600.0.26.4).
Type :help for assistance.
  1> enum Foo { case bar }
  2> String(reflecting: Foo.bar)
$R0: String = "__lldb_expr_1.Foo.bar"
```

2. Applications that use uniffi-rs may want to add their own `LocalizedError` implementation, because it's a generic type that can be used to display error messages directly to end users. They can't do that if the generated error types already conforms to `LocalizedError`.

**Comment by crazytonyli** [comment]
To be honest, I don't think uniffi-rs should add `LocalizedError` implementations at all. Because it simply can do the _localization_ part properly.

If you have to implement it, Rust `error.to_string()` might be a better choice than Swift `String(reflecting:)`

**Comment by mhammond** [comment]
heh, just re-found #2305. I think we added it because of some assumptions in our consumers, but I'm sure they just want a string to log etc. So yeah, maybe we should look at removing it.

**Comment by crazytonyli** [comment]
Hi @mhammond , any update on this PR?

**Review by mhammond — APPROVED** [review]
I dug back a bit and I don't think removing it entirely is reasonable, so this is great, thanks!

**Comment by mhammond** [comment]
Sorry, I mean to talk to som

**Pull request merged**
