### PR TITLE
Upgrade cargo_metadata

### PR DESCRIPTION
**Pull request by jplatte**

### CODE REVIEW

**Comment by bendk** [comment]
How important is the `clap` upgrade?  That upgrade would require some work to vendor in to the mozilla central tree.  I don't think it's a ton of work, but if it's not needed maybe I would wait on the upgrade.

**Comment by jplatte** [comment]
I see this whole PR only as cleanup. I don't really care whether it's merged now or in a month.

**Comment by skhamis** [comment]
I might not understand the full effects of this update mozilla central, so I'll switch this to someone who might have more context

**Comment by badboy** [comment]
I can take this

**Comment by badboy** [comment]
Ok, I looked. The `cargo_metadata` update is easy.
The clap update requires a whole bunch of new audits in m-c, for which I currently won't have the time, so I'd rather hold back on that for the time being.

**Comment by jplatte** [comment]
Should I split the PR, or can you cherry-pick the commit?

**Comment by badboy** [comment]
> Should I split the PR, or can you cherry-pick the commit?

Splitting it would be wonderful

**Comment by jplatte** [comment]
Done, clap upgrade is now https://github.com/mozilla/uniffi-rs/pull/1383.

**Review by badboy — APPROVED** [review]
> [@jplatte](https://github.com/jplatte) pushed 0 commits.

:D

**Comment by jplatte** [comment]
It should have said `-1` 😄

**Pull request merged**
