### PR TITLE
Refactor Path(Buf) usage

### PR DESCRIPTION
**Pull request by jplatte**

### CODE REVIEW

**Comment by jplatte** [comment]
This simplifies the code by only using `AsRef` generics where functions are actually being called from different places, not converting the `camino::Utf8Path`s received from `cargo_metadata` to Strings (because they're actually very nice to work with directly!) and cleaning up some error handling.

**Review by bendk — APPROVED** [review]
Nice set of cleanups/refactors!

**Comment by jplatte** [comment]
So it's approved, what else needs to happen before merge? 😄

**Comment by bendk** [comment]
Oops, meant to merge this yesterday.

**Pull request merged**
