### PR TITLE
Create python tutorial.

### PR DESCRIPTION
**Pull request by gogo2464**
Fixes https://github.com/mozilla/uniffi-rs/issues/1642

Fell free to ask question or suggest a review.

### CODE REVIEW

**Comment by gogo2464** [comment]
I hope the link does not seems to be an add.

**Comment by mhammond** [comment]
Thanks for the contribution. I can't speak for the other maintainers, but personally I'd prefer a living example in the repo. In particular, I'm concerned that the example will grow stale over time, particularly as Rust and Python evolve, and that it's literally impossible even today to verify whether that example actually works (which isn't to say I don't think it does work, it's just that it will be impossible to know whether it works on Python 3.14). A stand-alone example, with all files checked in, and from where `setup.py` can be run to create a `.wheel` (or whatever it creates :) would be ideal - we could then even run it from CI (ie, the fact the artifact can be created without error would become part of our tests). It might even be possible/reasonable to have CI install and run the artifact on a set of different Python versions.

Having it be real living code might also help people contribute so it ends up being a representation of "best practice" - eg, there are a couple of mildly hacky things in your setup.py, which might very well be the best way to handle the situation, but there might be others who might have different or better ways - but it will be impossible for them to contribute those ideas, because it's not a living example they can change.

Having the tutorial in markdown which helps describe the example and options for running it makes a lot of sense though and would be a valuable contribution.

What do you think about that?

**Comment by gogo2464** [comment]
Thank you for your attention.

Your question is absolutely legitimate. It is a big copy and past from what I did in this repository: https://github.com/gogo2464/cryptatools-rs/blob/master/cryptatools-core/setup.py

So I suggest to add it. Do you would like to add it instead of the tutorial or do you prefer to add it with the tutorial on how to create exactly the same file please?

**Comment by mhammond** [comment]
I'm not sure adding that setup.py makes sense as it would require adding your entire project as the sample. I was thinking something like creating a very small "hello world" uniffi component and using that - in other words, it being the smallest possible `setup.py` and smallest possible demo code that actually creates a .wheel and tests it.

I haven't thought this through very much, but maybe a structure like:
examples/distributing # a new dir
examples/distributing/rust # has Cargo.toml, and src/ with a "hello world" example.
examples/distributing/python # has setup.py and (say) test.py (which assumes the wheel as been installed) and README.MD to explain how it works.
examples/distributing/kotlin # in the future someone might add this which uses the same "../rust"

And a new small section in the manual could summarize this and point to the directory.

Like I said, haven't really thought that through, so I'm open to ideas!

**Comment by gogo2464** [comment]
Good idea. Could you create your own repo on mozilla account please? I would like to fork and merge.

**Comment by mhammond** [comment]
> Good idea. Could you create your own repo on mozilla account please? I would like to fork and merge.

I'm not sure what you mean?

**Comment by gogo2464** [comment]
I was asking if I can push on a mozilla repo instead of creating my own repo for the python uniffi example.

I am currently creating a new repo to avoid to loose time.

**Comment by gogo2464** [comment]
Could someone create a ruby tutorial please?

**Comment by gogo2464** [comment]
Done! sounds so great! https://github.com/gogo2464/minimal-uniffi-rs-setuptools-python-example/tree/master

**Comment by gogo2464** [comment]
Seems good for me.

**Comment by mhammond** [comment]
You might have misunderstood me.

> I'm not sure adding that setup.py makes sense as it would require adding your entire project as the sample.
> ...
>  The smallest possible `setup.py` and smallest possible demo code that actually creates a .wheel and tests it.
> I haven't thought this through very much, but maybe a structure like:
> * examples/distributing # a new dir

I meant there should be a PR which adds the "smallest possible demo code" to a new `examples/distributing` directory in the UniFFI repo, plus a few notes in the UniFFI manual pointing at it. We don't want to link to an external repo for any of that.

**Comment by gogo2464** [comment]
Seems perfect now.

**Comment by mhammond** [comment]
🤦

**Comment by gogo2464** [comment]
I am so sorry I just forgot to delete the .git folder, file or something like this!!!! I was trying to put the full repo as example in the list of examples! I never tried to set it as sumbmodule!

**Comment by gogo2464** [comment]
I am going to add a distributing folder. Could you reopen my PR please? I spent a full day !

**Comment by gogo2464** [comment]
I am sorry

**Comment by gogo2464** [comment]
@mhammond I have put it back it the real place https://github.com/gogo2464/uniffi-rs/commit/ae2c72c66defcfc5d51c0ea09de01c6c6fb3b18b

**Comment by mhammond** [comment]
I'm sorry you are misunderstanding, I've done my best to explain. This PR needs to update to change only files in this repo and have no links to external repos.

**Comment by gogo2464** [comment]
Should I remove the file docs/manual/src/python/examples_projects.md ? It is not an issue. I can do it!

**Comment by gogo2464** [comment]
I did it https://github.com/gogo2464/uniffi-rs/commit/8c896d34f50f9910af57b434586f44707452d62c

**Comment by mhammond** [comment]
You keep linking to a commit on your fork - I can't do anything with that.

**Comment by gogo2464** [comment]
You are probably confused with the new link that replaced the old and points to mozilla origin repository: https://github.com/gogo2464/uniffi-rs/commit/8c896d34f50f9910af57b434586f44707452d62c#diff-67a560e438c6ffcdce7d26267bc97328517483392697c4a36bc07e3de894e30eR12 .

 It is written: "
The full example is available at this [address](https://github.com/mozilla/uniffi-rs/tree/main/examples/distributing/uniffi-rust-to-python-library/src/setup.py). In order to reproduce the issue, let's see some points about the setup.py file." IT does not points to any external repository.  If I am wrong, could you point to the line please?


 the PR is closed and can not be updated. Do you mean I should create another PR?

**Comment by mhammond** [comment]
> You are probably confused with the new link that replaced the old and points to mozilla origin repository: https://github.com/gogo2464/uniffi-rs/commit/8c896d34f50f9910af57b434586f44707452d62c#diff-67a560e438c6ffcdce7d26267bc97328517483392697c4a36bc07e3de894e30eR12 .

I don't think I'm the confused one. This is a PR - there is a tab near the top titled "Files Changed". You need to arrange so that has the changes you are proposing. I'm not going to follow any links you post to your repo and the list of "Files Changed" must not contain any links to your repo. This is how PRs work on github - maybe you need to find some introductory resources to how PRs work?

> the PR is closed and can not be updated. Do you mean I should create another PR?

If course it can - the PR is based on a branch you own. It appears that branch hasn't been updated since you first opened the PR.

**Comment by jplatte** [comment]
@mhammond Once a PR is closed, further pushing to the branch will not update the PR (and in fact, it will also prevent the PR from being reopened).

**Comment by gogo2464** [comment]
Absolutely. What has been pointed out by @jplatte is entierely what I was trying to say. This is why I show you my own fork instead of this https://github.com/mozilla/uniffi-rs/pull/1643/files.

Do not watch https://github.com/mozilla/uniffi-rs/pull/1643/files. watch this instead https://github.com/gogo2464/uniffi-rs/commit/8c896d34f50f9910af57b434586f44707452d62c please.

I am also merging my 3 commits in order to let a link added in the history that has been deleted next.

Sorry for the lack of communication.

**Comment by mhammond** [comment]
oops, well TIL about that, so yeah, please open a new PR.  I'm really hoping I can help you get something landed.

**Comment by gogo2464** [comment]
Thanks. No problem. :)

**Pull request closed without merging**
