### PR TITLE
uniffi is all grown up so gets its own matrix room

### PR DESCRIPTION
**Pull request by mhammond**
(considered renaming "matrix" to "element" because that's what my tab title seems to be, and I'm still confused what the difference is, but wiki.m.o still says "matrix", so 🤷 )

### CODE REVIEW

**Comment by badboy** [comment]
Matrix is the network, protocol & server.
Element is the (web) client. Formerly known as Vector (briefly) and then Riot.im (longer).

**Review by badboy — APPROVED** [review]

**Comment by mhammond** [comment]
Thanks!

> Matrix is the ..., Element is the...

Yeah - but in this context I need to choose one word ;)

**Comment by mhammond** [comment]
(I guess I was trying to make a theatrical point about needing to choose one work :)

**Comment by badboy** [comment]
[What is the Matrix?](https://www.youtube.com/watch?v=O5b0ZxUWNf0)

**Pull request merged**
