### PR TITLE
Add throws annotation to kotlin exceptions

### PR DESCRIPTION
**Pull request by l-maia**
A PR adding the throw annotation as identified in issue #1098, to provide compatibility with Java.

### CODE REVIEW

**Comment by bendk** [comment]
Seems like a good idea, but does this mean the exceptions must be caught in Java?  I'm wondering if this could be configurable either globally or on a per-function basis.  What do you think?

**Comment by l-maia** [comment]
Yes, kotlin does not have checked exceptions so the Java signatures of Kotlin exceptions, so in Java it won't have an indication than an exception is to be thrown unless the annotation is used.

I think it is safer to have the exceptions and handling them in Java, than not having them at all.

https://kotlinlang.org/docs/java-to-kotlin-interop.html#checked-exceptions

**Comment by mhammond** [comment]
huh - that link implies that the annotation is needed to make it *possible* to catch the exceptions in java - which surprises me, but I should learn to stop being surprised by Kotlin and Java :) @jhugman is our resident Kotlin expert, so hopefully he will weigh in, but at face value this LGTM.

**Comment by jhugman** [comment]
This looks great. Thank you so much for your contribution.

I think the only thing I'd ask before landing this would be to do the same for the `uniffi_bindgen/src/bindings/kotlin/templates/TopLevelFunctionTemplate.kt` file, which would need similar annotations.

**Review by jhugman — CHANGES_REQUESTED** [review]
Just adding this a formal review.

**Review by jhugman — APPROVED** [review]
This looks great, thank you so much.

**Comment by jhugman** [comment]
There is one conflict in the `ObjectTemplate.kt` could you resolve this (or I can for you) and then we can hit the Big Green Button!

**Pull request closed without merging**
